import '@servicenow/sdk/global'
import { BusinessRule, ClientScript, ReferenceColumn, StringColumn, Table } from '@servicenow/sdk/core'
import { showStateUpdate } from '../server/script.js'

//creates a client script that pops up 'Table loaded successfully!!' message every time todo record is loaded
ClientScript({
    $id: Now.ID['cs0'],
    name: 'my_client_script',
    table: 'incident',
    active: true,
    applies_extended: false,
    global: true,
    ui_type: 'all',
    description: 'Custom client script generated by Now SDK',
    messages: '',
    isolate_script: false,
    type: 'onLoad',
    script: script`function onLoad() {
        g_form.addInfoMessage("Table loaded successfully!!")
    }`,
})

//creates a business rule that pops up state change message whenever a todo record is updated
// test comment
BusinessRule({
    $id: Now.ID['br0'],
    action: ['update'],
    table: 'incident',
    script: showStateUpdate,
    name: 'LogStateChange',
    order: 100,
    when: 'after',
    active: true,
    abort_action: false,
})

export const x_692302_pf_manage_pf_users = Table({
    name: 'x_692302_pf_manage_pf_users',
    label: 'PF User',
    extends: 'task',
    auto_number: {
        prefix: 'PFUSR',
        number: 1000,
        number_of_digits: 9,
    },
    schema: {
        u_pf_user_name: ReferenceColumn({
            label: 'Name',
            attributes: {},
            maxLength: 32,
            referenceTable: 'sys_user',
            mandatory: true,
        }),
        u_pf_account: StringColumn({
            label: 'PF Account',
            mandatory: true,
            maxLength: 40,
        }),
        u_uan: StringColumn({
            label: 'UAN Number',
            mandatory: true,
            maxLength: 40,
        }),
        name: StringColumn({
            label: 'XNAME',
            maxLength: 40,
        }),
    },
    actions: ['read', 'update', 'create'],
})
